language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:

before_install:
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- command -v conda >/dev/null || { wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
   bash miniconda.sh -b -f -p $MINICONDA; }
- conda update --yes conda
- conda remove --yes -n condaenv --all
- conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
- conda install --yes -n condaenv pip
- source activate condaenv
- conda install --yes -c obspy pytest flake8 sphinx python=$TRAVIS_PYTHON_VERSION
- pip install coveralls 
- pip install requests responses

install:
- python setup.py install --record installed_files.txt

script:
- nosetests -v --with-coverage --cover-package=seismogram_noise
- flake8 --ignore E402,N802,N806 `find seismogram_noise/* -name \*.py | grep -v setup.py | grep -v /doc/`

after_success:
- coveralls

before_cache:
# clean unused packages & installed files from conda cache
# this makes the cache rebuilt less frequently
- conda clean --yes --tarballs --packages --index-cache
- rm -rf $HOME/miniconda/pkgs/cache
- xargs rm <installed_files.txt

cache:
  directories:
    - $HOME/miniconda
